package com.hourglassapps.util;

import java.util.Iterator;

/***
 * A Iterator, that records any Exception generated by it. 
 * Any such Exception is thrown when the throwCaught method is invoked at regular intervals during the iteration.
 * @author kieran
 *
 * @param <T>
 */
public interface ThrowableIterator<T> extends Iterator<T>, Thrower {
}
